properties:
  farmaceutId?:
    example: 1
    type: number
    format: int
  username:
    example: Example
    type: string
  password:
    example: Example
    type: string
  email:
    example: Example
    type: string
  ime:
    example: Example
    type: string
  prezime:
    example: Example
    type: string
  brojDozvole:
    example: 1
    type: number
