properties:
  lijekId?:
    example: 1
    type: number
    format: int
  naziv:
    example: Example
    type: string
  opis:
    example: Example
    type: string
  kolicina:
    example: 1
    type: number
    format: int
  cijena:
    example: 1
    type: number
    format: int
  kategorija:
    example: 1
    type: number
    format: int
