properties:
  pacijentId?:
    example: 1
    type: number
    format: int
  ime:
    example: Example
    type: string
  prezime:
    example: Example
    type: string
  datumRodjenja:
    example: 2020-05-06
    type: date-only
  sifraZdravstvene:
    example: 1
    type: number
    format: int
