properties:
  racunId?:
    example: 1
    type: number
    format: int
  datum:
    example: 2020-05-06
    type: date-only
  suma:
    example: 1
    type: number
    format: int
  recept?:
    example: 1
    type: number
    format: int
  nacinPlacanja:
    example: 1
    type: number
    format: int
  farmaceut:
    example: 1
    type: number
    format: int
